-- Profile Schema: Discord-Style HUD & Protocol Themes

-- 1. Profiles Table Updates (Schema Cache Fix)
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS full_name TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS display_name TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS avatar_url TEXT;

-- 2. Library Protocols (Theme Hoisting)
-- Ensure master_theme exists for card painting
ALTER TABLE public.protocol_stacks ADD COLUMN IF NOT EXISTS master_theme TEXT;
-- Also check legacy table just in case
CREATE TABLE IF NOT EXISTS public.library_protocols (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
ALTER TABLE public.library_protocols ADD COLUMN IF NOT EXISTS master_theme TEXT;
