-- Archive v6.0 Schema Hardening

-- 1. Library Habits (The Atoms)
ALTER TABLE library_habits ADD COLUMN IF NOT EXISTS slug TEXT UNIQUE;
ALTER TABLE library_habits ADD COLUMN IF NOT EXISTS theme TEXT;
ALTER TABLE library_habits ADD COLUMN IF NOT EXISTS icon TEXT;
ALTER TABLE library_habits ADD COLUMN IF NOT EXISTS category TEXT;

-- 2. User Habits (The Active Rig)
-- We need to carry over instructions and themes for the user's specific instance
ALTER TABLE habits ADD COLUMN IF NOT EXISTS theme TEXT;
ALTER TABLE habits ADD COLUMN IF NOT EXISTS how_instruction TEXT;
ALTER TABLE habits ADD COLUMN IF NOT EXISTS why_instruction TEXT;
ALTER TABLE habits ADD COLUMN IF NOT EXISTS slug TEXT; -- To trace back to source atom

-- 3. Library Protocols (The Stacks)
-- Switching from integer ID to text ID (e.g., 'stack_atlas') is a breaking change for the primary key if we enforced int before.
-- 'library_protocols' was created with 'id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'.
-- We will add a 'slug' or 'stack_id' column for the text ID and make it unique.
ALTER TABLE library_protocols ADD COLUMN IF NOT EXISTS stack_id TEXT UNIQUE;
ALTER TABLE library_protocols ADD COLUMN IF NOT EXISTS expert_voice TEXT;
ALTER TABLE library_protocols ADD COLUMN IF NOT EXISTS theme_override TEXT;
ALTER TABLE library_protocols ADD COLUMN IF NOT EXISTS overrides JSONB DEFAULT '[]'::jsonb;

-- Change habit_ids (UUID[]) to habit_slugs (TEXT[]) or just add a new column.
-- The JSON uses slugs in the 'habits' array.
ALTER TABLE library_protocols ADD COLUMN IF NOT EXISTS habit_slugs TEXT[];
