-- Sovereignty Infrastructure Migrations

-- 1. Profiles Table Updates
-- Ensure membership_tier exists with default 'initiate'
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS membership_tier text DEFAULT 'initiate' CHECK (membership_tier IN ('initiate', 'operator', 'sovereign', 'architect', 'admin'));

-- Ensure neural_config exists (JSONB for user settings/AI context)
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS neural_config JSONB DEFAULT '{}'::jsonb;


-- 2. Library Protocols (Templates)
CREATE TABLE IF NOT EXISTS library_protocols (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    habit_ids UUID[], -- Array of UUIDs referring to library_habits
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Library Habits (Source of Truth for Protocols)
-- This table holds the 'master' definitions of habits that can be copied to a user's list
CREATE TABLE IF NOT EXISTS library_habits (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    unit TEXT, -- e.g., 'minutes', 'reps', 'checkbox'
    target_value INTEGER DEFAULT 1, -- Default target
    type TEXT CHECK (type IN ('absolute', 'frequency', 'unit')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS Policies (Implicitly required but SQL provided for completeness)
-- library_protocols: Public Read, Admin Write
ALTER TABLE library_protocols ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Protocols" ON library_protocols FOR SELECT USING (true);
-- library_habits: Public Read, Admin Write
ALTER TABLE library_habits ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Library Habits" ON library_habits FOR SELECT USING (true);
