-- Iron Skeleton Fix: Persistence Fracture Repair & Vault Stabilization

-- 1. Admin Promotion
UPDATE public.profiles SET role = 'ROOT_ADMIN' WHERE email = 'admin@maximost.com';

-- 2. Schema Healing
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS full_name TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS display_name TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS callsign TEXT;
ALTER TABLE public.habits ADD COLUMN IF NOT EXISTS display_order INTEGER DEFAULT 0;
ALTER TABLE public.habits ADD COLUMN IF NOT EXISTS circadian_window TEXT;

-- 3. Writing Gates (RLS)
DROP POLICY IF EXISTS "Users can manage their own habits" ON public.habits;
DROP POLICY IF EXISTS "Users can manage their own logs" ON public.habit_logs;
DROP POLICY IF EXISTS "Users can manage their own memories" ON public.user_memories;
DROP POLICY IF EXISTS "Users can manage their own entries" ON public.journal_entries;

-- Create FOR ALL policies
CREATE POLICY "Users can manage their own habits" ON public.habits FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can manage their own logs" ON public.habit_logs FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can manage their own memories" ON public.user_memories FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- 4. Lore Hydration (v12 Metadata)
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Footprints","theme":"bio_emerald","is_ring":true},"compiler":{"atom":"Movement Baseline","step":"Incidental movement","why":"Biological engine maintenance. [Universal]","expert":"Universal"},"telemetry":{"auto_verify":true,"terra_metric":"activity.steps","window":"flexible"},"tactical":"Incidental movement","identity":"Biological engine maintenance. [Universal]"}'::jsonb WHERE slug = 'daily_steps';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Sun","theme":"bio_emerald"},"compiler":{"atom":"Photon Anchoring","step":"Outdoor light within 30m of wake","why":"Resets the central clock and sleep timer. [Panda]","canon_ref":"The Circadian Code"},"telemetry":{"auto_verify":false,"window":"morning"},"tactical":"Outdoor light within 30m of wake","identity":"Resets the central clock and sleep timer. [Panda]"}'::jsonb WHERE slug = 'morning_sun';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Timer","theme":"asset_lime"},"compiler":{"atom":"Metabolic Switch","step":"16-hour fast. Water/Black Coffee only.","why":"Triggers autophagy and insulin stability. [Attia]","canon_ref":"Outlive"},"tactical":"16-hour fast. Water/Black Coffee only.","identity":"Triggers autophagy and insulin stability. [Attia]"}'::jsonb WHERE slug = 'fasting';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Flame","theme":"combat_red"},"compiler":{"atom":"Hormetic Heat","step":"Dry sauna at 174°F minimum.","why":"Activates Heat Shock Proteins to prevent decay. [Patrick]"},"tactical":"Dry sauna at 174°F minimum.","identity":"Activates Heat Shock Proteins to prevent decay. [Patrick]"}'::jsonb WHERE slug = 'sauna';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Snowflake","theme":"oxygen_cyan"},"compiler":{"atom":"Cold Shock","step":"Neck-deep submersion <50°F.","why":"250% dopamine increase and mental callousing. [Huberman]"},"tactical":"Neck-deep submersion <50°F.","identity":"250% dopamine increase and mental callousing. [Huberman]"}'::jsonb WHERE slug = 'cold_plunge';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Dumbbell","theme":"slate_steel"},"compiler":{"atom":"Neural Drive","step":"Compound movements (Squat/Press).","why":"Primary predictor of healthspan and integrity. [Galpin]","canon_ref":"Muscle Physiology"},"tactical":"Compound movements (Squat/Press).","identity":"Primary predictor of healthspan and integrity. [Galpin]"}'::jsonb WHERE slug = 'heavy_lifting';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Zap","theme":"neural_violet"},"compiler":{"atom":"Cognitive Isolation","step":"No phone. No internet. Single-task focus.","why":"Focus x Time = High Quality Output. [Newport]","canon_ref":"Deep Work"},"tactical":"No phone. No internet. Single-task focus.","identity":"Focus x Time = High Quality Output. [Newport]"}'::jsonb WHERE slug = 'deep_work';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"PenTool","theme":"warning_amber"},"compiler":{"atom":"Radical Honesty","step":"5m nightly review of failures/lies.","why":"Data truth is the only path to growth. [Stoic]"},"tactical":"5m nightly review of failures/lies.","identity":"Data truth is the only path to growth. [Stoic]"}'::jsonb WHERE slug = 'shadow_audit';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"RefreshCw","theme":"bio_emerald"},"compiler":{"atom":"Tissue Maintenance","step":"Couch stretch and deep squat hold.","why":"Offset the contractures of 21st-century sitting. [Starrett]","canon_ref":"Becoming a Supple Leopard"},"tactical":"Couch stretch and deep squat hold.","identity":"Offset the contractures of 21st-century sitting. [Starrett]"}'::jsonb WHERE slug = 'ready_state';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Wind","theme":"oxygen_cyan"},"compiler":{"atom":"Carbon Tolerance","step":"Nose breathing during sleep/exercise.","why":"Efficient oxygen delivery via the Bohr Effect. [McKeown]","canon_ref":"Breath"},"tactical":"Nose breathing during sleep/exercise.","identity":"Efficient oxygen delivery via the Bohr Effect. [McKeown]"}'::jsonb WHERE slug = 'nasal_breathing';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Dna","theme":"asset_lime"},"compiler":{"atom":"Leucine Trigger","step":"30g+ protein in the first meal.","why":"Threshold required for muscle protein synthesis. [Layman]"},"tactical":"30g+ protein in the first meal.","identity":"Threshold required for muscle protein synthesis. [Layman]"}'::jsonb WHERE slug = 'protein_loading';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Moon","theme":"bio_rig"},"compiler":{"atom":"Glymphatic Clearance","step":"Cool room (65°F). Total darkness.","why":"Clears amyloid beta neurotoxins from the brain. [Walker]","canon_ref":"Why We Sleep"},"tactical":"Cool room (65°F). Total darkness.","identity":"Clears amyloid beta neurotoxins from the brain. [Walker]"}'::jsonb WHERE slug = 'sleep_hygiene';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Activity","theme":"telemetry"},"compiler":{"atom":"Aerobic Power","step":"4 mins Max Effort / 4 mins Rest x 4.","why":"Strongest correlate to lifespan. [Attia]"},"tactical":"4 mins Max Effort / 4 mins Rest x 4.","identity":"Strongest correlate to lifespan. [Attia]"}'::jsonb WHERE slug = 'vo2_max';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Shield","theme":"slate_steel"},"compiler":{"atom":"Discipline Baseline","step":"Precision bed-make upon waking.","why":"First victory establishes the standard. [Jocko]","canon_ref":"Extreme Ownership"},"tactical":"Precision bed-make upon waking.","identity":"First victory establishes the standard. [Jocko]"}'::jsonb WHERE slug = 'make_bed';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Heart","theme":"ghost_white"},"compiler":{"atom":"Narrative Control","step":"10m of meditation or prayer for others.","why":"Interrupts the ego; resets Internal Force. [Aurelius]","canon_ref":"Meditations"},"tactical":"10m of meditation or prayer for others.","identity":"Interrupts the ego; resets Internal Force. [Aurelius]"}'::jsonb WHERE slug = 'prayer_stillness';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Heart","theme":"neural_violet"},"compiler":{"atom":"Character Forge","step":"One helpful act in total secrecy.","why":"Virtue for its own sake, not for praise. [Aurelius]"},"tactical":"One helpful act in total secrecy.","identity":"Virtue for its own sake, not for praise. [Aurelius]"}'::jsonb WHERE slug = 'good_deed';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Lock","theme":"ghost_white"},"compiler":{"atom":"Perspective Strike","step":"Reflect for 2m: ''This could be my last day.''","why":"Kills procrastination instantly. High ground. [Seneca]","canon_ref":"Letters from a Stoic"},"tactical":"Reflect for 2m: ''This could be my last day.''","identity":"Kills procrastination instantly. High ground. [Seneca]"}'::jsonb WHERE slug = 'memento_mori';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Moon","theme":"sunset_indigo"},"compiler":{"atom":"Melatonin Protection","step":"Screens off 60m before bed.","why":"Ensures deep REM and hormonal reset. [Walker]"},"tactical":"Screens off 60m before bed.","identity":"Ensures deep REM and hormonal reset. [Walker]"}'::jsonb WHERE slug = 'digital_sunset';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Lock","theme":"combat_red"},"compiler":{"atom":"Metabolic Shield","step":"Zero refined sugar or liquid calories.","why":"Reduces systemic inflammation and energy crashes. [Lustig]"},"tactical":"Zero refined sugar or liquid calories.","identity":"Reduces systemic inflammation and energy crashes. [Lustig]"}'::jsonb WHERE slug = 'glycemic_defense';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Users","theme":"maxi_blue"},"compiler":{"atom":"Tribe Connection","step":"Connect with one person for 10+ mins.","why":"Social isolation is a biological stressor. [Conti]","canon_ref":"Trauma"},"tactical":"Connect with one person for 10+ mins.","identity":"Social isolation is a biological stressor. [Conti]"}'::jsonb WHERE slug = 'social_sync';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"BookOpen","theme":"neural_violet"},"compiler":{"atom":"Neural Plasticity","step":"30m focused practice on a high-leverage skill.","why":"Growth requires both Focus and Novelty. [Huberman]"},"tactical":"30m focused practice on a high-leverage skill.","identity":"Growth requires both Focus and Novelty. [Huberman]"}'::jsonb WHERE slug = 'skill_acquisition';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"RotateCcw","theme":"sunset_indigo"},"compiler":{"atom":"Cognitive Closure","step":"Review tomorrow''s Big 3. Say ''Shutdown Complete''.","why":"Clears attention residue for recovery. [Newport]"},"tactical":"Review tomorrow''s Big 3. Say ''Shutdown Complete''.","identity":"Clears attention residue for recovery. [Newport]"}'::jsonb WHERE slug = 'daily_shutdown';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Anchor","theme":"telemetry"},"compiler":{"atom":"Force Output","step":"Total of 120s hanging from a bar.","why":"Grip strength is the #1 proxy for longevity. [Bohannon]"},"tactical":"Total of 120s hanging from a bar.","identity":"Grip strength is the #1 proxy for longevity. [Bohannon]"}'::jsonb WHERE slug = 'dead_hang';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Wind","theme":"oxygen_cyan"},"compiler":{"atom":"Vagus Nerve Stim","step":"Inhale 4, Hold 4, Exhale 4, Hold 4.","why":"Tactical autonomic nervous system regulation. [McKeown]"},"tactical":"Inhale 4, Hold 4, Exhale 4, Hold 4.","identity":"Tactical autonomic nervous system regulation. [McKeown]"}'::jsonb WHERE slug = 'box_breathing';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Trees","theme":"bio_emerald"},"compiler":{"atom":"Panoramic Vision","step":"15m outside. Look at horizon. No phone.","why":"Fractals reduce rumination and blood pressure. [Bratman]"},"tactical":"15m outside. Look at horizon. No phone.","identity":"Fractals reduce rumination and blood pressure. [Bratman]"}'::jsonb WHERE slug = 'touch_grass';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Mail","theme":"slate_steel"},"compiler":{"atom":"Open Loop Closure","step":"Process inbox until empty. Archive or Task.","why":"Unfinished tasks leak cognitive energy. [Ferriss]","canon_ref":"4-Hour Workweek"},"tactical":"Process inbox until empty. Archive or Task.","identity":"Unfinished tasks leak cognitive energy. [Ferriss]"}'::jsonb WHERE slug = 'inbox_zero';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Lock","theme":"black_box"},"compiler":{"atom":"Dopamine Reset","step":"Phone in a separate room during deep work.","why":"Severing the connection to the digital hive mind. [Lembke]","canon_ref":"Dopamine Nation"},"tactical":"Phone in a separate room during deep work.","identity":"Severing the connection to the digital hive mind. [Lembke]"}'::jsonb WHERE slug = 'digital_air_gap';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Brain","theme":"nav_computer"},"compiler":{"atom":"Narrative Control","step":"Journal to identify ''Defense'' vs ''Generative'' drive.","why":"Regain agency by identifying internal ''spies''. [Conti]"},"tactical":"Journal to identify ''Defense'' vs ''Generative'' drive.","identity":"Regain agency by identifying internal ''spies''. [Conti]"}'::jsonb WHERE slug = 'agency_audit';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"TrendingUp","theme":"kinetic_core"},"compiler":{"atom":"Leverage Check","step":"Did you use Code, Media, or Capital today?","why":"Wealth = Leverage x Judgment. [Naval]","canon_ref":"The Almanack of Naval Ravikant"},"tactical":"Did you use Code, Media, or Capital today?","identity":"Wealth = Leverage x Judgment. [Naval]"}'::jsonb WHERE slug = 'leverage_audit';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Activity","theme":"bio_rig"},"compiler":{"atom":"Lipolysis","step":"20m walk before first calorie.","why":"Mobilize fatty acids immediately upon waking. [Horowitz]"},"tactical":"20m walk before first calorie.","identity":"Mobilize fatty acids immediately upon waking. [Horowitz]"}'::jsonb WHERE slug = 'fasted_walk';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Thermometer","theme":"bio_rig"},"compiler":{"atom":"Core Temp Drop","step":"Bedroom at 65°F one hour before sleep.","why":"Biological trigger for deep sleep onset. [Walker]"},"tactical":"Bedroom at 65°F one hour before sleep.","identity":"Biological trigger for deep sleep onset. [Walker]"}'::jsonb WHERE slug = 'cold_bedroom';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Zap","theme":"neural_violet"},"compiler":{"atom":"Neural Recharge","step":"10-20 min audio guide for deep rest.","why":"Dopamine recovery without sleep. [Huberman]"},"tactical":"10-20 min audio guide for deep rest.","identity":"Dopamine recovery without sleep. [Huberman]"}'::jsonb WHERE slug = 'nsdr_reset';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Zap","theme":"asset_lime"},"compiler":{"atom":"Cognitive Fuel","step":"5g Creatine Monohydrate daily.","why":"Increases anaerobic power and brain function. [Attia]"},"tactical":"5g Creatine Monohydrate daily.","identity":"Increases anaerobic power and brain function. [Attia]"}'::jsonb WHERE slug = 'creatine_load';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Flame","theme":"combat_red"},"compiler":{"atom":"Mental Callousing","step":"Train until the mind wants to quit.","why":"Override the brain''s safety governor. [Goggins]"},"tactical":"Train until the mind wants to quit.","identity":"Override the brain''s safety governor. [Goggins]"}'::jsonb WHERE slug = 'taking_souls';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Trophy","theme":"warning_amber"},"compiler":{"atom":"Past Victories","step":"Recall a moment of immense suffering you overcame.","why":"Fuel for current struggle. [Goggins]"},"tactical":"Recall a moment of immense suffering you overcame.","identity":"Fuel for current struggle. [Goggins]"}'::jsonb WHERE slug = 'cookie_jar';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Eye","theme":"ghost_white"},"compiler":{"atom":"Raw Truth","step":"Face the mirror. State your insecurities.","why":"Strip the ego to see the raw data truth. [Goggins]"},"tactical":"Face the mirror. State your insecurities.","identity":"Strip the ego to see the raw data truth. [Goggins]"}'::jsonb WHERE slug = 'accountability_mirror';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Wind","theme":"oxygen_cyan"},"compiler":{"atom":"Exhale Timer","step":"Measure the duration of a single exhale.","why":"Proxy for CO2 tolerance and stress resilience. [Mackenzie]"},"tactical":"Measure the duration of a single exhale.","identity":"Proxy for CO2 tolerance and stress resilience. [Mackenzie]"}'::jsonb WHERE slug = 'carbon_tolerance';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Sun","theme":"maxi_blue"},"compiler":{"atom":"Sovereign Spirit","step":"Attend meeting or Outreach/Service.","why":"Honoring the 6.5 Year Mission. Isolation is drift.","expert":"Founder"},"tactical":"Attend meeting or Outreach/Service.","identity":"Honoring the 6.5 Year Mission. Isolation is drift."}'::jsonb WHERE slug = 'recovery_sync';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"RefreshCw","theme":"ghost_white"},"compiler":{"atom":"Love of Fate","step":"Embrace a current obstacle as necessary fuel.","why":"The hindrance is the path. [Aurelius]"},"tactical":"Embrace a current obstacle as necessary fuel.","identity":"The hindrance is the path. [Aurelius]"}'::jsonb WHERE slug = 'amor_fati';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Shield","theme":"ghost_white"},"compiler":{"atom":"Internal Focus","step":"Discard 3 external worries outside your control.","why":"Zero energy leak on things you cannot change. [Epictetus]"},"tactical":"Discard 3 external worries outside your control.","identity":"Zero energy leak on things you cannot change. [Epictetus]"}'::jsonb WHERE slug = 'dichotomy_control';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Moon","theme":"neural_violet"},"compiler":{"atom":"Sleep Stack","step":"Mg Threonate + Theanine 60m pre-bed.","why":"Reduce sleep latency and improve quality. [Huberman]"},"tactical":"Mg Threonate + Theanine 60m pre-bed.","identity":"Reduce sleep latency and improve quality. [Huberman]"}'::jsonb WHERE slug = 'sleep_cocktail';
UPDATE public.library_habits SET metadata = '{"visuals":{"icon":"Zap","theme":"combat_red"},"compiler":{"atom":"Governor Bypass","step":"Push for 5 more mins/reps when ''done''.","why":"The mind quits long before the body. [Goggins]"},"tactical":"Push for 5 more mins/reps when ''done''.","identity":"The mind quits long before the body. [Goggins]"}'::jsonb WHERE slug = 'forty_percent';
